# Generated by Django 2.1.5 on 2019-02-07 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='prod_price',
        ),
    ]
