# Generated by Django 2.1.5 on 2019-02-13 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_profileuser_is_vendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorAndProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('product_colour', models.CharField(max_length=50)),
                ('product_screen_size', models.CharField(max_length=10)),
                ('product_os', models.CharField(max_length=50)),
                ('product_ram', models.CharField(max_length=10)),
                ('product_memory', models.CharField(max_length=10)),
                ('product_price', models.PositiveIntegerField(default=0)),
                ('Product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
        ),
    ]
