# Generated by Django 2.1.5 on 2019-02-13 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_vendorandproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorandproduct',
            name='Product_id',
        ),
    ]
